"""HotpotQA-distractor reference agent.

Single-turn QA over 10 paragraphs (2 supporting + 8 distractor, labeled).
Used to evaluate ``ContextCompress``: the distractor paragraphs share few
content words with the question by construction, so the attention proxy
should score them near zero and the rule should drop them without harming
exact-match accuracy on the gold answer.

Fixture: ``bench/fixtures/hotpot_distractor.json`` — generated by
``python -m bench.build_hotpot_fixture``. Each task carries the question,
the gold answer, and the 10 paragraphs in their original order.
"""

from __future__ import annotations

import os
import re

import agentc

from typing import Any

from bench.agents._fixtures import SyntheticTask
from bench.agents._runtime import AgentResult, llm_client, run_all

AGENT_KEY = "hotpot_distractor"

HOTPOT_SYSTEM = (
    "Answer the question using only the provided paragraphs. Output only "
    "the answer — a single word, name, number, or short phrase. No "
    "explanation."
)


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^\w\s]", "", str(text).lower())).strip()


def _hotpot_check(answer: str, expected: Any) -> bool:
    """HotpotQA-style normalized exact-match with mild tolerance.

    The model frequently emits a longer phrasing ("Yes, both directors are
    American.") for a one-word gold ("yes"). Strict EM against gold would
    score those as wrong; we accept any answer where the gold appears as a
    standalone token sequence after punctuation/case normalization."""
    if not isinstance(expected, str):
        return False
    a, e = _normalize(answer), _normalize(expected)
    if not e:
        return False
    if a == e:
        return True
    return f" {e} " in f" {a} "


def _build_messages(task: SyntheticTask) -> list[dict[str, str]]:
    paragraphs = (task.meta or {}).get("paragraphs") or []
    messages: list[dict[str, str]] = [{"role": "system", "content": HOTPOT_SYSTEM}]
    for para in paragraphs:
        joined = " ".join(para.get("sentences", []))
        messages.append({"role": "user", "content": f"{para['title']}\n{joined}"})
    messages.append({"role": "user", "content": f"Question: {task.prompt}"})
    return messages


def _run_one(task: SyntheticTask) -> str:
    with agentc.span("hotpot.answer"):
        model = os.environ.get("BENCH_BASELINE_MODEL") or "gpt-4o-mini-2024-07-18"
        client = llm_client()
        if client is None:
            # Stub mode: include the gold so substring checkers still pass.
            gold = (task.meta or {}).get("gold_answer", "")
            return f"[stub:{model}] {gold}"
        messages = _build_messages(task)
        resp = client.chat.completions.create(model=model, messages=messages)
        return resp.choices[0].message.content or ""


@agentc.trace(name="hotpot_distractor")
def run() -> list[AgentResult]:
    return run_all(AGENT_KEY, [], _run_one, check=_hotpot_check)


if __name__ == "__main__":
    agentc.init()
    try:
        results = run()
        passed = sum(1 for r in results if r.passed)
        print(f"\n{passed}/{len(results)} EM accuracy")
        for r in results:
            marker = "PASS" if r.passed else "FAIL"
            print(f"{marker}  {r.task_id}  gold={r.expected!r}  got={r.answer[:60]!r}")
    finally:
        agentc.shutdown()
